In [1]:
import numpy as np

In [4]:
np.arange()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [6]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [7]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [8]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [9]:
np.random.rand(1)

array([0.05413261])

In [10]:
np.random.randn(25)

array([-0.72337164, -0.69009637, -0.35370246,  1.60618064, -0.42772992,
       -0.89241589, -0.6697595 , -0.2791551 , -1.20657933,  1.12401155,
        0.9632737 ,  2.63258455,  0.73050776, -0.39335649, -2.44667828,
        2.41033623,  0.05321836, -0.46946298, -0.69120525,  0.43743817,
        2.18464857, -0.55189276, -0.80411855, -2.09368446,  0.26547989])

In [16]:
np.arange(0,101).reshape(10,10) / 100

ValueError: cannot reshape array of size 101 into shape (10,10)