In [1]:
import numpy as np


In [2]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [4]:
ranarr

array([12, 34, 40, 17, 26, 24, 38, 43, 29, 15])

In [6]:
arr.shape

(25,)

In [7]:
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [8]:
arr.reshape(2,25)

ValueError: cannot reshape array of size 25 into shape (2,25)

In [9]:
arr.shape


(25,)

In [14]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [15]:
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [19]:
Mylist = ]

In [21]:
print(Mylist)

[range(0, 31)]


In [22]:
Mylist

[range(0, 31)]

In [24]:
np.arange(0,31)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [34]:
deva=np.arange(0,31)

In [35]:
deva

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [42]:
deva.reshape(1,31)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]])

In [44]:
deva.shape

(31,)

In [49]:
np.random.rand(3,20)

array([[0.84589874, 0.26114583, 0.9200679 , 0.71651387, 0.01742362,
        0.14600717, 0.5850478 , 0.26091543, 0.61012153, 0.31972211,
        0.87413322, 0.32290449, 0.5056637 , 0.24487277, 0.18203282,
        0.99096027, 0.16549731, 0.09177414, 0.18590446, 0.20594737],
       [0.28498211, 0.32971516, 0.43842016, 0.72131964, 0.8527817 ,
        0.88844039, 0.44201768, 0.1975346 , 0.45989093, 0.97477816,
        0.20129633, 0.13893906, 0.01751216, 0.63273689, 0.85252874,
        0.01641692, 0.6692379 , 0.27258246, 0.58827802, 0.61205756],
       [0.48793872, 0.79939346, 0.54168154, 0.41305125, 0.53499906,
        0.91332224, 0.35959822, 0.5866366 , 0.93419273, 0.34887789,
        0.50886806, 0.90147517, 0.15652736, 0.87486554, 0.8699416 ,
        0.6638604 , 0.58532768, 0.30737441, 0.2496969 , 0.45948313]])

In [50]:
np.random.randn(3,20)

array([[-0.38579045,  0.2389071 ,  0.26838716,  0.70428282,  0.98264432,
         0.90537735, -0.34787787,  0.26771766, -0.17491254,  1.36758819,
         0.97334175,  0.72030331,  0.31802448, -1.6387471 ,  0.26546612,
        -0.96449878, -0.52641907,  0.73881947, -2.04597103,  0.04528616],
       [-0.3947365 , -1.88291005, -0.6075701 , -2.09554939,  1.43984671,
         0.13398232, -0.90323056,  1.12905654, -0.21615674, -0.08812632,
         0.91795979,  0.10055709, -1.30339757, -1.2448534 , -0.26540429,
        -0.85209843, -0.02799624,  1.22280199,  1.7745351 , -0.64079403],
       [-0.80576178, -0.09834463,  0.23681666, -1.36684951, -0.57059896,
        -1.30723744, -1.19568482,  1.70933106, -0.04793127,  1.14607567,
         0.56273166, -1.40300452,  1.68878802,  0.39113497,  0.27396702,
         2.46107534, -1.12481542,  0.04251556, -0.08178348,  1.42412694]])

In [53]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [56]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [57]:
np.zeros((5,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [58]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [59]:
np.ones((5,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [60]:
np.linspace(0,31,5)

array([ 0.  ,  7.75, 15.5 , 23.25, 31.  ])

In [61]:
mylist = [1,2,3,4,5]

In [63]:
np.array(mylist)

array([1, 2, 3, 4, 5])

In [64]:
np.arange(0,16)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [65]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [66]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [69]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [70]:
np.ones((5,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [72]:
np.linspace(0,16,5)

array([ 0.,  4.,  8., 12., 16.])

In [73]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [76]:
np.random.rand(5)

array([0.85939606, 0.1695752 , 0.27237264, 0.4611119 , 0.24963875])

In [77]:
np.random.randn(10)

array([ 1.02571932e+00,  6.67837572e-01,  1.97065671e+00, -1.20154158e+00,
        5.33538298e-01,  1.68784125e-03,  5.38223750e-01, -1.64254268e+00,
       -1.37992185e-01, -9.09935041e-01])

In [79]:
np.random.randint(0,100)

91

In [80]:
deva =np.arange(0,16)

In [81]:
deva

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [88]:
deva.reshape(16,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15]])

In [86]:
deva.shape

(16,)

In [89]:
deva.dtype

dtype('int32')